import type { ServiceFaq } from "@/types";

/**
 * FAQs por servicio (clave = slug). Bilingüe. Se usan en la página de
 * detalle del servicio y para el JSON-LD FAQPage.
 */
export const SERVICE_FAQS: Record<string, ServiceFaq[]> = {
  "condiciones-cronicas": [
    {
      question: "¿Cada cuánto debo hacerme exámenes de control?",
      answer: "Con diabetes, A1C cada 3 meses hasta estabilizarte y luego cada 6. Con presión alta o colesterol, laboratorio cada 6 a 12 meses según tus resultados y medicamentos. Te damos un calendario personalizado.",
      questionEn: "How often should I get follow-up labs?",
      answerEn: "With diabetes, A1C every 3 months until stable and then every 6. With high blood pressure or cholesterol, labs every 6 to 12 months depending on your results and medications. We give you a personalized schedule.",
    },
    {
      question: "¿Qué valor de A1C significa diabetes?",
      answer: "Entre 5.7 y 6.4 es prediabetes; 6.5 o más es diabetes. Si ya tienes diabetes, la meta habitual es mantenerla por debajo de 7, aunque el médico la ajusta a tu caso.",
      questionEn: "What A1C level means diabetes?",
      answerEn: "5.7 to 6.4 is prediabetes; 6.5 or higher is diabetes. If you already have diabetes, the usual goal is to keep it below 7, though the physician adjusts it to your case.",
    },
    {
      question: "¿Pueden recetarme y surtir mis medicamentos?",
      answer: "Sí. El médico ajusta o inicia tu tratamiento y puedes surtirlo en nuestra farmacia, con opciones económicas. Trae tus medicamentos actuales o la lista con dosis.",
      questionEn: "Can you prescribe and fill my medications?",
      answerEn: "Yes. The physician adjusts or starts your treatment and you can fill it at our pharmacy, with low-cost options. Bring your current medications or a list with doses.",
    },
    {
      question: "Perdí mi seguimiento porque ya no tengo seguro, ¿puedo retomarlo aquí?",
      answer: "Sí. No necesitas seguro; la consulta y el laboratorio tienen precio fijo. Trae tus últimos resultados o recetas si los tienes y retomamos el control desde ahí.",
      questionEn: "I lost my follow-up because I no longer have insurance. Can I resume it here?",
      answerEn: "Yes. No insurance needed; the visit and lab work have a flat price. Bring your latest results or prescriptions if you have them and we pick up your care from there.",
    },
    {
      question: "¿Tengo que venir en ayunas a la consulta de control?",
      answer: "Solo si ese día te vamos a medir glucosa en ayunas o colesterol: 8 a 12 horas sin comer, agua sí. Toma tus medicamentos como siempre salvo indicación contraria.",
      questionEn: "Do I need to fast for my follow-up visit?",
      answerEn: "Only if we are measuring fasting glucose or cholesterol that day: 8 to 12 hours without food, water is fine. Take your medications as usual unless told otherwise.",
    },
    {
      question: "¿Necesito cita para el control de diabetes o presión?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. Si prefieres un horario fijo para tus controles, llámanos y lo reservamos.",
      questionEn: "Do I need an appointment for diabetes or blood pressure care?",
      answerEn: "No. We see walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. If you prefer a set time for your checkups, call us and we reserve it.",
    },
  ],
  "tiroides": [
    {
      question: "¿Qué prueba se usa para revisar la tiroides?",
      answer: "Usamos principalmente la TSH y, si es necesario, T3 y T4 para evaluar cómo funciona tu tiroides.",
      questionEn: "What test is used to check the thyroid?",
      answerEn: "We mainly use TSH and, if needed, T3 and T4 to evaluate how your thyroid is working.",
    },
    {
      question: "¿Necesito cita previa?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. También puedes llamarnos para reservar un horario.",
      questionEn: "Do I need an appointment?",
      answerEn: "No. We welcome walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. You can also call us to reserve a time.",
    },
    {
      question: "¿Atienden a pacientes sin seguro?",
      answer: "Sí. No necesitas seguro médico; manejamos precios accesibles y transparentes. Pregúntanos por el costo antes de tu visita.",
      questionEn: "Do you accept patients without insurance?",
      answerEn: "Yes. You don't need insurance; we offer affordable, transparent pricing. Ask us about the cost before your visit.",
    },
  ],
  "alergias": [
    {
      question: "¿Cómo sé si es alergia o un resfriado?",
      answer: "La alergia da estornudos, comezón en nariz y ojos y moco claro durante semanas, sin fiebre ni dolor de cuerpo. El resfriado dura 7 a 10 días y suele traer fiebre o malestar. Si hay duda, te evaluamos y descartamos flu o COVID.",
      questionEn: "How do I know if it is an allergy or a cold?",
      answerEn: "An allergy causes sneezing, itchy nose and eyes and clear mucus for weeks, without fever or body aches. A cold lasts 7 to 10 days and usually brings fever or malaise. If in doubt, we evaluate you and rule out flu or COVID.",
    },
    {
      question: "¿Hacen pruebas de alergia?",
      answer: "Sí. La mayoría se diagnostica con la historia clínica y la exploración; cuando hace falta, hacemos análisis de sangre (IgE) para identificar los alérgenos más comunes, con resultados en pocos días.",
      questionEn: "Do you do allergy testing?",
      answerEn: "Yes. Most allergies are diagnosed from the history and exam; when needed, we run blood tests (IgE) to identify the most common allergens, with results in a few days.",
    },
    {
      question: "¿Tratan alergias en la piel y ronchas?",
      answer: "Sí. Urticaria, dermatitis, reacciones a productos y picaduras inflamadas. Te damos tratamiento para cortar la comezón desde el primer día y, en crisis intensas, una inyección que alivia en minutos.",
      questionEn: "Do you treat skin allergies and hives?",
      answerEn: "Yes. Hives, dermatitis, reactions to products and swollen insect bites. We give you treatment to stop the itching from day one and, for severe flare-ups, an injection that brings relief in minutes.",
    },
    {
      question: "¿Los medicamentos para la alergia dan sueño?",
      answer: "Los antihistamínicos de nueva generación que usamos no dan sueño en la mayoría de las personas, así que puedes trabajar y manejar con normalidad. Los sprays nasales y las gotas tampoco.",
      questionEn: "Do allergy medications cause drowsiness?",
      answerEn: "The newer-generation antihistamines we use do not cause drowsiness in most people, so you can work and drive normally. Nasal sprays and eye drops do not either.",
    },
    {
      question: "¿Atienden a niños con alergias?",
      answer: "Sí. Evaluamos y tratamos rinitis, tos alérgica y alergias en la piel en niños, con dosis y medicamentos adecuados a su edad. Deben venir acompañados por su madre, padre o tutor.",
      questionEn: "Do you see children with allergies?",
      answerEn: "Yes. We evaluate and treat rhinitis, allergic cough and skin allergies in children, with age-appropriate doses and medications. They must come with a parent or legal guardian.",
    },
    {
      question: "¿Necesito cita o seguro para la consulta de alergias?",
      answer: "No. Ven sin cita de lunes a sábado de 9 AM a 9 PM o domingo de 9 AM a 7 PM. No necesitas seguro; la consulta tiene precio fijo y los medicamentos se pueden surtir en nuestra farmacia.",
      questionEn: "Do I need an appointment or insurance for an allergy visit?",
      answerEn: "No. Walk in Monday to Saturday from 9 AM to 9 PM or Sunday from 9 AM to 7 PM. No insurance needed; the visit has a flat price and medications can be filled at our pharmacy.",
    },
  ],
  "enfermedades-respiratorias": [
    {
      question: "¿Hacen prueba de flu y de COVID el mismo día?",
      answer: "Sí. Con un solo hisopado nasal tienes el resultado de influenza A y B y de COVID-19 en unos 15 minutos, y el tratamiento sale en la misma visita.",
      questionEn: "Do you test for flu and COVID the same day?",
      answerEn: "Yes. With a single nasal swab you get the result for influenza A and B and COVID-19 in about 15 minutes, and treatment is started during the same visit.",
    },
    {
      question: "¿Cuándo debo hacerme la prueba?",
      answer: "En los primeros 2 a 3 días de síntomas. Ahí la prueba es más precisa y los antivirales para la influenza todavía sirven; después de 48 horas su efecto es menor.",
      questionEn: "When should I get tested?",
      answerEn: "Within the first 2 to 3 days of symptoms. That is when the test is most accurate and flu antivirals still work; after 48 hours their benefit is smaller.",
    },
    {
      question: "¿Me van a dar antibiótico para la gripe?",
      answer: "No, porque la gripe y el COVID son virus y el antibiótico no los cura. Solo lo indicamos cuando hay una infección bacteriana, como estreptococo o sinusitis prolongada.",
      questionEn: "Will you give me an antibiotic for the flu?",
      answerEn: "No, because the flu and COVID are viruses and antibiotics do not cure them. We prescribe one only when there is a bacterial infection, such as strep or prolonged sinusitis.",
    },
    {
      question: "¿Atienden a niños con fiebre y tos?",
      answer: "Sí. Hacemos las pruebas rápidas y tratamos a niños de todas las edades; deben venir acompañados por su madre, padre o tutor. En bebés menores de 3 meses con fiebre, ven de inmediato.",
      questionEn: "Do you see children with fever and cough?",
      answerEn: "Yes. We run rapid tests and treat children of all ages; they must come with a parent or legal guardian. For babies under 3 months with fever, come right away.",
    },
    {
      question: "¿Me dan justificante para el trabajo o la escuela?",
      answer: "Sí. Te entregamos la constancia de la consulta y del reposo indicado, así como el resultado de la prueba por escrito si tu empleador lo pide.",
      questionEn: "Do you provide a note for work or school?",
      answerEn: "Yes. We give you a note for the visit and the recommended time off, as well as the written test result if your employer requires it.",
    },
    {
      question: "¿Atienden sin cita los fines de semana?",
      answer: "Sí. Abrimos de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM, sin cita y sin seguro, con precio fijo para la consulta y las pruebas.",
      questionEn: "Do you see walk-ins on weekends?",
      answerEn: "Yes. We are open Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM, with no appointment or insurance, at a flat price for the visit and tests.",
    },
  ],
  "examen-fisico-escolar": [
    {
      question: "¿Llenan el formulario de la escuela, el equipo o el trabajo?",
      answer: "Sí. Trae el formulario de tu escuela, equipo deportivo o empleador y lo completamos durante la visita, el mismo día.",
      questionEn: "Do you fill out the school, team or employer form?",
      answerEn: "Yes. Bring your school, sports-team or employer form and we complete it during the visit, the same day.",
    },
    {
      question: "¿Hacen exámenes físicos para adultos?",
      answer: "Sí. Además de los físicos escolares y deportivos, hacemos exámenes físicos para el trabajo y chequeos anuales para adultos, con análisis de sangre y orina si los necesitas.",
      questionEn: "Do you do physical exams for adults?",
      answerEn: "Yes. Besides school and sports physicals, we do work physicals and annual checkups for adults, with blood and urine tests if needed.",
    },
    {
      question: "¿Necesito ir en ayunas?",
      answer: "Solo si te vas a hacer análisis de sangre como glucosa o colesterol. En ese caso ven con 8 a 10 horas de ayuno; puedes tomar agua. Para el físico escolar o deportivo no hace falta.",
      questionEn: "Do I need to fast?",
      answerEn: "Only if you're having blood work such as glucose or cholesterol. In that case, come after fasting 8 to 10 hours; water is fine. School and sports physicals don't require fasting.",
    },
    {
      question: "¿Cuánto cuesta el examen físico?",
      answer: "Tenemos precios accesibles y sin sorpresas; el costo depende de si necesitas laboratorio. Llámanos y te lo decimos antes de tu visita, o pregunta por el chequeo general completo por $99.",
      questionEn: "How much does the physical exam cost?",
      answerEn: "We offer affordable pricing with no surprises; the cost depends on whether you need lab work. Call us and we'll tell you before your visit, or ask about the $99 complete general checkup.",
    },
    {
      question: "¿Necesito cita previa?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. También puedes llamarnos para reservar un horario.",
      questionEn: "Do I need an appointment?",
      answerEn: "No. We welcome walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. You can also call us to reserve a time.",
    },
    {
      question: "¿Atienden a pacientes sin seguro?",
      answer: "Sí. No necesitas seguro médico; manejamos precios accesibles y transparentes. Pregúntanos por el costo antes de tu visita.",
      questionEn: "Do you accept patients without insurance?",
      answerEn: "Yes. You don't need insurance; we offer affordable, transparent pricing. Ask us about the cost before your visit.",
    },
  ],
  "ginecologia": [
    {
      question: "¿Cada cuánto debo hacerme el papanicolaou?",
      answer: "De los 21 a los 65 años, cada 3 años si el resultado es normal, o cada 5 años cuando se combina con la prueba de VPH después de los 30. Si nunca te lo has hecho, empieza hoy sin cita.",
      questionEn: "How often should I get a Pap smear?",
      answerEn: "From age 21 to 65, every 3 years if the result is normal, or every 5 years when combined with HPV testing after 30. If you have never had one, start today with no appointment.",
    },
    {
      question: "¿Puedo hacerme el papanicolaou si tengo la regla?",
      answer: "Es mejor esperar a que pase el sangrado abundante para que la muestra sea confiable. También evita relaciones, duchas vaginales y óvulos 48 horas antes.",
      questionEn: "Can I get a Pap smear during my period?",
      answerEn: "It is better to wait until heavy bleeding is over so the sample is reliable. Also avoid intercourse, douching and vaginal suppositories for 48 hours before.",
    },
    {
      question: "¿Cuánto tarda el resultado del papanicolaou?",
      answer: "Entre 1 y 2 semanas. Te avisamos cuando llegue y, si sale alterado, te lo explicamos con calma y organizamos el seguimiento.",
      questionEn: "How long do Pap smear results take?",
      answerEn: "1 to 2 weeks. We let you know when it arrives and, if it is abnormal, we explain it calmly and arrange follow-up.",
    },
    {
      question: "¿Tratan las infecciones vaginales el mismo día?",
      answer: "Sí. Tomamos el cultivo para saber si es hongos, vaginosis o tricomoniasis y en la mayoría de los casos empiezas el tratamiento en la misma visita. La promoción de salud íntima femenina por $69 incluye cultivo, consulta y examen de orina.",
      questionEn: "Do you treat vaginal infections the same day?",
      answerEn: "Yes. We take a culture to determine whether it is yeast, bacterial vaginosis or trichomoniasis, and in most cases you start treatment during the same visit. The $69 women's intimate health promotion includes the culture, consultation and urine test.",
    },
    {
      question: "¿Atienden a adolescentes y primeras consultas?",
      answer: "Sí. Atendemos desde la adolescencia; las menores de edad deben venir acompañadas por su madre, padre o tutor. Explicamos cada paso antes de hacerlo para que la primera consulta sea tranquila.",
      questionEn: "Do you see teenagers and first-time patients?",
      answerEn: "Yes. We see patients from adolescence on; minors must come with a parent or legal guardian. We explain each step before doing it so the first visit feels comfortable.",
    },
    {
      question: "¿Necesito cita o seguro para la consulta ginecológica?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM, y no necesitas seguro médico. Si prefieres, llámanos para reservar un horario y conocer el precio.",
      questionEn: "Do I need an appointment or insurance for a gynecology visit?",
      answerEn: "No. We see walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM, and no health insurance is needed. If you prefer, call us to reserve a time and ask about the price.",
    },
  ],
  "prueba-embarazo": [
    {
      question: "¿Cuándo puedo hacerme la prueba de embarazo?",
      answer: "La prueba de orina es confiable desde el primer día de retraso. Si quieres saberlo antes, la prueba de sangre detecta el embarazo entre 7 y 10 días después de la concepción.",
      questionEn: "When can I take a pregnancy test?",
      answerEn: "The urine test is reliable from the first day of a missed period. If you want to know sooner, the blood test detects pregnancy 7 to 10 days after conception.",
    },
    {
      question: "¿Es mejor la prueba de orina o la de sangre?",
      answer: "Las dos son confiables. La de orina es rápida y suficiente en la mayoría de los casos; la de sangre detecta antes y mide el nivel exacto de la hormona, útil en embarazos muy tempranos o si hay dolor o sangrado. El médico te orienta.",
      questionEn: "Is the urine or blood test better?",
      answerEn: "Both are reliable. The urine test is quick and enough in most cases; the blood test detects earlier and measures the exact hormone level, useful in very early pregnancies or if there is pain or bleeding. The physician guides you.",
    },
    {
      question: "¿Me dan el resultado el mismo día?",
      answer: "La prueba de orina se lee en minutos, en la misma visita. La de sangre suele estar lista en 24 horas y te avisamos por teléfono o en persona, como prefieras.",
      questionEn: "Do I get the result the same day?",
      answerEn: "The urine test is read in minutes, during the same visit. The blood test is usually ready within 24 hours and we notify you by phone or in person, whichever you prefer.",
    },
    {
      question: "¿Puedo confirmar el embarazo con ultrasonido ahí mismo?",
      answer: "Sí. A partir de la sexta semana hacemos el ultrasonido en la misma clínica para ver el saco, el latido y calcular la fecha probable de parto.",
      questionEn: "Can I confirm the pregnancy with an ultrasound there?",
      answerEn: "Yes. From the sixth week we do the ultrasound in the same clinic to see the sac and heartbeat and calculate your due date.",
    },
    {
      question: "¿La prueba es confidencial?",
      answer: "Sí. Se hace en un consultorio privado, el resultado solo se comparte contigo y, como pagas directamente sin seguro, no llega ningún documento a tu casa.",
      questionEn: "Is the test confidential?",
      answerEn: "Yes. It is done in a private exam room, the result is shared only with you and, since you pay directly without insurance, no paperwork is mailed to your home.",
    },
    {
      question: "¿Necesito cita y cuánto cuesta la prueba de embarazo?",
      answer: "No necesitas cita ni seguro. Atendemos de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM; el precio es accesible y te lo confirmamos por teléfono.",
      questionEn: "Do I need an appointment and how much does the pregnancy test cost?",
      answerEn: "No appointment or insurance needed. We are open Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM; the price is affordable and we confirm it by phone.",
    },
  ],
  "anticonceptivos": [
    {
      question: "¿Qué métodos anticonceptivos ofrecen en la clínica?",
      answer: "Pastillas anticonceptivas, combinadas y de solo progestina, e inyección trimestral. Para implante o DIU te orientamos sobre dónde colocarlo, y si tienes un implante caducado lo retiramos aquí.",
      questionEn: "Which birth control methods do you offer?",
      answerEn: "Combined and progestin-only birth control pills, and the 3-month shot. For the implant or IUD we guide you on where to get one placed, and if you have an expired implant we remove it here.",
    },
    {
      question: "¿Puedo empezar el anticonceptivo el mismo día?",
      answer: "Sí, en la mayoría de los casos. Revisamos tu historial y tu presión, hacemos una prueba de embarazo y, si es seguro, inicias las pastillas o recibes la inyección en esa misma visita.",
      questionEn: "Can I start birth control the same day?",
      answerEn: "Yes, in most cases. We review your history and blood pressure, run a pregnancy test and, if it is safe, you start the pill or receive the shot during that same visit.",
    },
    {
      question: "¿Cada cuánto se pone la inyección anticonceptiva?",
      answer: "Cada 12 a 13 semanas. Te damos la fecha exacta de la siguiente dosis; si te retrasas más de 13 semanas, usa condón y ven lo antes posible.",
      questionEn: "How often is the birth control shot given?",
      answerEn: "Every 12 to 13 weeks. We give you the exact date of your next dose; if you are more than 13 weeks late, use condoms and come as soon as possible.",
    },
    {
      question: "¿Los anticonceptivos me protegen de las infecciones de transmisión sexual?",
      answer: "No. Ni las pastillas ni la inyección protegen contra ETS. Combínalos con condón si tienes una pareja nueva o varias parejas, y hazte pruebas periódicamente.",
      questionEn: "Does birth control protect me from sexually transmitted infections?",
      answerEn: "No. Neither the pill nor the shot protects against STDs. Combine them with condoms if you have a new partner or several partners, and get tested regularly.",
    },
    {
      question: "¿Necesito receta o seguro médico?",
      answer: "No. La consulta y el método se pagan directamente con precio fijo, sin seguro. Si necesitas receta para surtir tus pastillas, te la damos en la misma visita.",
      questionEn: "Do I need a prescription or health insurance?",
      answerEn: "No. The visit and the method are paid directly at a flat price, without insurance. If you need a prescription to fill your pills, we give it to you during the same visit.",
    },
    {
      question: "¿Atienden sin cita para anticonceptivos?",
      answer: "Sí, de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. Las menores de edad deben venir acompañadas por su madre, padre o tutor.",
      questionEn: "Do you see walk-ins for birth control?",
      answerEn: "Yes, Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. Minors must come with a parent or legal guardian.",
    },
  ],
  "extraccion-implantes": [
    {
      question: "¿Duele la extracción del implante?",
      answer: "Solo el piquete de la anestesia local. Después no sientes dolor durante el procedimiento, que dura entre 10 y 20 minutos. Los días siguientes puede haber un moretón y molestia leve.",
      questionEn: "Does implant removal hurt?",
      answerEn: "Only the poke of the local anesthetic. After that you feel no pain during the procedure, which takes 10 to 20 minutes. In the following days there may be a bruise and mild soreness.",
    },
    {
      question: "¿Cuánto tiempo dura el implante anticonceptivo?",
      answer: "Tres años según la etiqueta, y en algunos casos hasta cinco según indicación médica. Después de esa fecha ya no es confiable y debe retirarse o cambiarse.",
      questionEn: "How long does the contraceptive implant last?",
      answerEn: "Three years per the label, and in some cases up to five per medical guidance. After that date it is no longer reliable and should be removed or replaced.",
    },
    {
      question: "¿Cuándo puedo quedar embarazada después de quitarlo?",
      answer: "Muy pronto: la fertilidad suele regresar en el primer mes. Si no buscas embarazo, usa condón desde el día de la extracción o inicia otro método en la misma visita.",
      questionEn: "How soon can I get pregnant after removal?",
      answerEn: "Very soon: fertility usually returns within the first month. If you are not trying to get pregnant, use condoms from the day of removal or start another method during the same visit.",
    },
    {
      question: "¿Qué pasa si no se siente el implante en el brazo?",
      answer: "No lo extraemos a ciegas. Hacemos un ultrasonido para localizarlo y, si está muy profundo, te referimos con un especialista para que se retire con seguridad. Trae tu tarjeta de colocación si la tienes.",
      questionEn: "What if the implant cannot be felt in my arm?",
      answerEn: "We do not remove it blindly. We do an ultrasound to locate it and, if it is very deep, refer you to a specialist so it can be removed safely. Bring your placement card if you have it.",
    },
    {
      question: "¿Me quedan puntos o cicatriz?",
      answer: "No se necesitan puntos; la incisión es de 2 a 3 milímetros y se cierra con cintas adhesivas. Queda una cicatriz muy pequeña que se aclara con los meses.",
      questionEn: "Will I have stitches or a scar?",
      answerEn: "No stitches are needed; the incision is 2 to 3 millimeters and is closed with adhesive strips. A very small scar remains and fades over the months.",
    },
    {
      question: "¿Necesito cita o seguro para retirar el implante?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. No necesitas seguro; el procedimiento tiene precio fijo que te confirmamos por teléfono.",
      questionEn: "Do I need an appointment or insurance for implant removal?",
      answerEn: "No. We see walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. No insurance needed; the procedure has a flat price we confirm by phone.",
    },
  ],
  "salud-hombre": [
    {
      question: "¿Qué incluye el examen del hombre?",
      answer: "Incluye antígeno prostático (PSA), nivel de testosterona y un chequeo general, con resultados explicados en español.",
      questionEn: "What does the men's exam include?",
      answerEn: "It includes prostate antigen (PSA), testosterone level and a general checkup, with results explained in Spanish.",
    },
    {
      question: "¿Necesito cita previa?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. También puedes llamarnos para reservar un horario.",
      questionEn: "Do I need an appointment?",
      answerEn: "No. We welcome walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. You can also call us to reserve a time.",
    },
    {
      question: "¿Atienden a pacientes sin seguro?",
      answer: "Sí. No necesitas seguro médico; manejamos precios accesibles y transparentes. Pregúntanos por el costo antes de tu visita.",
      questionEn: "Do you accept patients without insurance?",
      answerEn: "Yes. You don't need insurance; we offer affordable, transparent pricing. Ask us about the cost before your visit.",
    },
  ],
  "examenes-sangre": [
    {
      question: "¿Necesito ir en ayunas para el análisis de sangre?",
      answer: "Solo para glucosa, colesterol y triglicéridos: entre 8 y 12 horas sin comer, agua sí. Para A1C, tiroides, B12 o pruebas hormonales no hace falta ayunar. Si tienes dudas, llámanos antes de venir.",
      questionEn: "Do I need to fast for blood work?",
      answerEn: "Only for glucose, cholesterol and triglycerides: 8 to 12 hours without food, water is fine. A1C, thyroid, B12 or hormone tests do not require fasting. If in doubt, call us before you come.",
    },
    {
      question: "¿En cuánto tiempo están los resultados?",
      answer: "La mayoría de las pruebas de rutina están listas en 24 a 48 horas y algunas el mismo día. Cuando llegan, un médico los revisa contigo en español y te entrega tu copia impresa.",
      questionEn: "How soon are results ready?",
      answerEn: "Most routine tests are ready in 24 to 48 hours, and some the same day. When they arrive, a physician reviews them with you and gives you a printed copy.",
    },
    {
      question: "¿Necesito una orden médica para hacerme análisis?",
      answer: "No. Puedes pedir la prueba que necesitas directamente en la clínica. Si traes una orden de otro médico o de tu empleador, la seguimos tal cual; si no, nuestro médico te orienta sobre qué pruebas te convienen.",
      questionEn: "Do I need a doctor's order for lab tests?",
      answerEn: "No. You can request the test you need directly at the clinic. If you bring an order from another doctor or your employer we follow it as written; otherwise our physician helps you choose the right tests.",
    },
    {
      question: "¿Cuánto cuesta un análisis de sangre sin seguro?",
      answer: "Depende de las pruebas. Tenemos paquetes con precio fijo, como el chequeo general completo por $99 con sangre, A1C, orina y consulta incluida, y cada prueba también se puede hacer por separado. Te damos el precio exacto antes de tomar la muestra.",
      questionEn: "How much does blood work cost without insurance?",
      answerEn: "It depends on the tests. We have flat-price packages, such as the complete general checkup for $99 with blood panel, A1C, urine test and consultation included, and every test can also be ordered separately. We give you the exact price before drawing your sample.",
    },
    {
      question: "¿Puedo hacerme los análisis el fin de semana y sin cita?",
      answer: "Sí. Tomamos muestras sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. Si vas a venir en ayunas, lo más cómodo es llegar temprano.",
      questionEn: "Can I get blood work on the weekend without an appointment?",
      answerEn: "Yes. We draw samples with no appointment Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. If you are fasting, coming early is the most comfortable option.",
    },
    {
      question: "¿Me explican los resultados aunque no tenga seguro?",
      answer: "Sí. La explicación con el médico es parte del servicio. Si algo sale fuera de rango, iniciamos el tratamiento o el seguimiento en la misma visita.",
      questionEn: "Will someone explain my results even if I have no insurance?",
      answerEn: "Yes. The review with the physician is part of the service. If something is out of range, we start treatment or follow-up during the same visit.",
    },
  ],
  "infecciones-urinarias": [
    {
      question: "¿Puedo recibir tratamiento el mismo día?",
      answer: "Sí, hacemos el examen de orina y, si hay infección, iniciamos el tratamiento el mismo día.",
      questionEn: "Can I get treatment the same day?",
      answerEn: "Yes, we run the urine test and, if there's an infection, we start treatment the same day.",
    },
    {
      question: "¿Necesito cita previa?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. También puedes llamarnos para reservar un horario.",
      questionEn: "Do I need an appointment?",
      answerEn: "No. We welcome walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. You can also call us to reserve a time.",
    },
    {
      question: "¿Atienden a pacientes sin seguro?",
      answer: "Sí. No necesitas seguro médico; manejamos precios accesibles y transparentes. Pregúntanos por el costo antes de tu visita.",
      questionEn: "Do you accept patients without insurance?",
      answerEn: "Yes. You don't need insurance; we offer affordable, transparent pricing. Ask us about the cost before your visit.",
    },
  ],
  "examen-heces": [
    {
      question: "¿Cómo se toma la muestra de heces?",
      answer: "Te damos un frasco estéril. Evacúa sobre papel limpio sin que la muestra toque agua ni orina, toma una porción del tamaño de una nuez con la cucharilla y tráela en menos de 2 horas, o refrigérala si no puedes venir de inmediato.",
      questionEn: "How do I collect a stool sample?",
      answerEn: "We give you a sterile container. Have the bowel movement onto clean paper without the sample touching water or urine, scoop a walnut-sized portion and bring it within 2 hours, or refrigerate it if you cannot come right away.",
    },
    {
      question: "¿Por qué piden tres muestras para parásitos?",
      answer: "Porque los parásitos no se eliminan todos los días. Con tres muestras de días distintos la probabilidad de encontrarlos es mucho mayor que con una sola.",
      questionEn: "Why do you ask for three samples for parasites?",
      answerEn: "Because parasites are not shed every day. With three samples from different days the chance of finding them is much higher than with a single one.",
    },
    {
      question: "¿En cuánto tiempo están los resultados del examen de heces?",
      answer: "El examen general y el de parásitos en 24 a 48 horas; el coprocultivo en 2 a 3 días. El médico te los explica y, si hay infección, te da el tratamiento en la misma clínica.",
      questionEn: "How soon are stool test results ready?",
      answerEn: "The general and parasite exams in 24 to 48 hours; the stool culture in 2 to 3 days. The physician explains them and, if there is an infection, gives you treatment in the same clinic.",
    },
    {
      question: "¿Puedo traer la muestra de mi hijo?",
      answer: "Sí. Recógela del pañal o del inodoro con la cucharilla del frasco, evitando la orina, y tráela el mismo día. Si necesitamos revisar al niño, debe venir con su madre, padre o tutor.",
      questionEn: "Can I bring my child's sample?",
      answerEn: "Yes. Collect it from the diaper or toilet with the container's scoop, avoiding urine, and bring it the same day. If we need to examine the child, they must come with a parent or legal guardian.",
    },
    {
      question: "¿Detectan la bacteria Helicobacter pylori en heces?",
      answer: "Sí. El antígeno de H. pylori en heces detecta la bacteria relacionada con gastritis y úlceras sin necesidad de endoscopia. Evita antiácidos y antibióticos las dos semanas previas para que el resultado sea confiable.",
      questionEn: "Can you detect Helicobacter pylori in stool?",
      answerEn: "Yes. The H. pylori stool antigen detects the bacterium linked to gastritis and ulcers without an endoscopy. Avoid antacids and antibiotics for the two weeks before so the result is reliable.",
    },
    {
      question: "¿Necesito cita o seguro para el examen de heces?",
      answer: "No. Pasa por el frasco cuando quieras de lunes a sábado de 9 AM a 9 PM o domingo de 9 AM a 7 PM y trae la muestra sin cita. No necesitas seguro; el precio es fijo.",
      questionEn: "Do I need an appointment or insurance for a stool test?",
      answerEn: "No. Pick up the container any time Monday to Saturday from 9 AM to 9 PM or Sunday from 9 AM to 7 PM and bring the sample with no appointment. No insurance needed; the price is flat.",
    },
  ],
  "prueba-strep": [
    {
      question: "¿Cuánto tarda el resultado del strep test?",
      answer: "Unos 10 minutos. Si sale positivo, sales con el antibiótico en la misma visita. Si sale negativo pero los síntomas son muy claros, podemos enviar un cultivo que confirma en 24 a 48 horas.",
      questionEn: "How long does the strep test take?",
      answerEn: "About 10 minutes. If it is positive, you leave with the antibiotic during the same visit. If it is negative but symptoms are very clear, we can send a culture that confirms in 24 to 48 hours.",
    },
    {
      question: "¿Cómo sé si mi dolor de garganta es estreptococo o un virus?",
      answer: "El estreptococo empieza de golpe, con fiebre, amígdalas inflamadas con placas y ganglios dolorosos, y sin tos ni mocos. Si hay tos, congestión o ronquera, lo más probable es un virus. La prueba lo confirma en minutos.",
      questionEn: "How do I know if my sore throat is strep or a virus?",
      answerEn: "Strep starts suddenly, with fever, swollen tonsils with patches and tender glands, and no cough or runny nose. If there is cough, congestion or hoarseness, a virus is more likely. The test confirms it in minutes.",
    },
    {
      question: "¿La prueba duele? Es para mi hijo.",
      answer: "No duele; es un hisopado de unos segundos en el fondo de la garganta que puede dar un poco de arcada. Lo hacemos rápido y con calma; los niños deben venir con su madre, padre o tutor.",
      questionEn: "Does the test hurt? It is for my child.",
      answerEn: "It does not hurt; it is a few-second swab at the back of the throat that may cause a slight gag. We do it quickly and calmly; children must come with a parent or legal guardian.",
    },
    {
      question: "¿Cuándo puedo volver a la escuela o al trabajo?",
      answer: "Después de 24 horas tomando el antibiótico y sin fiebre ya no contagias. Te damos un justificante con los días de reposo indicados por el médico.",
      questionEn: "When can I go back to school or work?",
      answerEn: "After 24 hours on the antibiotic and without fever you are no longer contagious. We give you a note with the days off recommended by the physician.",
    },
    {
      question: "¿Qué pasa si no trato el estreptococo?",
      answer: "Puede causar complicaciones como abscesos en la garganta, fiebre reumática que afecta al corazón o problemas en los riñones. Por eso es importante confirmarlo y terminar los 10 días de antibiótico.",
      questionEn: "What happens if strep is not treated?",
      answerEn: "It can cause complications such as throat abscesses, rheumatic fever that affects the heart or kidney problems. That is why it is important to confirm it and finish the 10 days of antibiotics.",
    },
    {
      question: "¿Necesito cita o seguro para la prueba de estreptococo?",
      answer: "No. Ven sin cita de lunes a sábado de 9 AM a 9 PM o domingo de 9 AM a 7 PM. No necesitas seguro; la consulta y la prueba tienen precio fijo y el antibiótico se surte en nuestra farmacia.",
      questionEn: "Do I need an appointment or insurance for a strep test?",
      answerEn: "No. Walk in Monday to Saturday from 9 AM to 9 PM or Sunday from 9 AM to 7 PM. No insurance needed; the visit and test have a flat price and the antibiotic is filled at our pharmacy.",
    },
  ],
  "prueba-tuberculosis": [
    {
      question: "¿Cuánto tarda la prueba de tuberculosis?",
      answer: "La aplicación toma menos de cinco minutos. Debes regresar entre 48 y 72 horas después para la lectura, que también es rápida, y ahí mismo te entregamos el resultado por escrito.",
      questionEn: "How long does the TB test take?",
      answerEn: "Placement takes less than five minutes. You return 48 to 72 hours later for the reading, which is also quick, and you get the written result right there.",
    },
    {
      question: "¿Qué pasa si no regreso a tiempo para la lectura?",
      answer: "La prueba pierde validez y hay que aplicarla de nuevo. Como abrimos los 7 días, te damos una fecha de lectura que te quede cómoda antes de que te vayas.",
      questionEn: "What if I miss the reading window?",
      answerEn: "The test becomes invalid and has to be placed again. Since we are open 7 days a week, we give you a convenient reading date before you leave.",
    },
    {
      question: "¿Me puedo bañar o trabajar con la prueba puesta?",
      answer: "Sí. Báñate con normalidad y haz tu vida diaria. Solo evita rascar la zona, tallarla con fuerza o cubrirla con curita o crema.",
      questionEn: "Can I shower or work with the test in place?",
      answerEn: "Yes. Shower normally and go about your day. Just avoid scratching the area, rubbing it hard or covering it with a bandage or cream.",
    },
    {
      question: "Tuve la vacuna BCG de niño, ¿la prueba me saldrá positiva?",
      answer: "Puede dar una reacción positiva aunque no tengas la infección. Dínoslo desde el inicio: el médico interpreta el resultado con ese dato y te orienta sobre los pasos a seguir, incluida una radiografía de tórax si hace falta.",
      questionEn: "I had the BCG vaccine as a child. Will my test be positive?",
      answerEn: "It can cause a positive reaction even without infection. Tell us at the start: the physician interprets the result with that in mind and guides you on next steps, including a chest X-ray if needed.",
    },
    {
      question: "¿Hacen la prueba de TB de dos pasos?",
      answer: "Sí. Aplicamos la primera prueba, la leemos, y si es negativa programamos la segunda entre una y tres semanas después, con su propia lectura, tal como piden hospitales y agencias de cuidado.",
      questionEn: "Do you do two-step TB testing?",
      answerEn: "Yes. We place the first test, read it, and if it is negative we schedule the second one to three weeks later with its own reading, just as hospitals and home-care agencies require.",
    },
    {
      question: "¿Necesito cita o seguro para la prueba de tuberculosis?",
      answer: "No. Ven sin cita de lunes a sábado de 9 AM a 9 PM o domingo de 9 AM a 7 PM. No hace falta seguro médico y el precio es fijo; llámanos para confirmarlo.",
      questionEn: "Do I need an appointment or insurance for the TB test?",
      answerEn: "No. Walk in Monday to Saturday from 9 AM to 9 PM or Sunday from 9 AM to 7 PM. No health insurance needed and the price is flat; call us to confirm it.",
    },
  ],
  "enfermedades-transmision-sexual": [
    {
      question: "¿Las pruebas de ETS son confidenciales?",
      answer: "Sí. La consulta es en un consultorio privado, el resultado solo se comparte contigo y, como pagas directamente sin seguro, no llega ninguna carta de aseguradora a tu casa.",
      questionEn: "Is STD testing confidential?",
      answerEn: "Yes. The visit is in a private exam room, the result is shared only with you and, since you pay directly without insurance, no insurer letter arrives at your home.",
    },
    {
      question: "¿Qué pruebas incluye el panel de ETS?",
      answer: "Clamidia, gonorrea, sífilis, VIH y hepatitis B y C; en mujeres se puede agregar cultivo para tricomoniasis, vaginosis y candidiasis. También puedes hacerte solo las pruebas que te preocupan.",
      questionEn: "What does the STD panel include?",
      answerEn: "Chlamydia, gonorrhea, syphilis, HIV and hepatitis B and C; for women a culture for trichomoniasis, bacterial vaginosis and yeast can be added. You can also order only the tests you are concerned about.",
    },
    {
      question: "¿Cuánto tardan los resultados?",
      answer: "La mayoría están listos en 2 a 3 días y algunos antes. Te avisamos por teléfono o en persona, como prefieras, y te explicamos qué significa cada uno.",
      questionEn: "How long do results take?",
      answerEn: "Most are ready in 2 to 3 days and some sooner. We notify you by phone or in person, whichever you prefer, and explain what each one means.",
    },
    {
      question: "¿Cuánto tiempo después del contacto puedo hacerme la prueba?",
      answer: "Clamidia y gonorrea se detectan de 1 a 2 semanas después, sífilis de 3 a 6 semanas y VIH de 2 a 6 semanas según la prueba. Si vienes antes, te hacemos lo que ya es válido y te decimos cuándo repetir el resto.",
      questionEn: "How soon after exposure can I get tested?",
      answerEn: "Chlamydia and gonorrhea are detectable 1 to 2 weeks after, syphilis 3 to 6 weeks and HIV 2 to 6 weeks depending on the test. If you come earlier, we run what is already valid and tell you when to repeat the rest.",
    },
    {
      question: "Si salgo positivo, ¿me dan el tratamiento ahí mismo?",
      answer: "En la mayoría de los casos sí: iniciamos los antibióticos en la misma visita y los tienes en nuestra farmacia. Para VIH o hepatitis te referimos con un especialista y te acompañamos.",
      questionEn: "If I test positive, do I get treatment right there?",
      answerEn: "In most cases yes: we start antibiotics during the same visit and you can get them at our pharmacy. For HIV or hepatitis we refer you to a specialist and support you.",
    },
    {
      question: "¿Debe hacerse la prueba mi pareja también?",
      answer: "Sí, es lo recomendable. Si tú sales positivo, tu pareja debe evaluarse y tratarse aunque no tenga síntomas; de lo contrario la infección puede volver. Pueden venir juntos o por separado.",
      questionEn: "Should my partner get tested too?",
      answerEn: "Yes, that is the recommendation. If you test positive, your partner should be evaluated and treated even without symptoms; otherwise the infection can come back. You can come together or separately.",
    },
  ],
  "examen-alcohol-drogas": [
    {
      question: "¿Pueden hacer la prueba de drogas y el examen físico el mismo día?",
      answer: "Sí. Si tu empleador pide ambos, hacemos la prueba de drogas y el examen físico para el trabajo en una sola visita, sin cita.",
      questionEn: "Can you do the drug test and the physical exam the same day?",
      answerEn: "Yes. If your employer requires both, we do the drug test and the work physical in a single walk-in visit.",
    },
    {
      question: "¿Entregan documentación para el trabajo?",
      answer: "Sí, te entregamos la documentación del resultado para tu empleador o trámite.",
      questionEn: "Do you provide documentation for work?",
      answerEn: "Yes, we give you documentation of the result for your employer or paperwork.",
    },
    {
      question: "¿Necesito cita previa?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. También puedes llamarnos para reservar un horario.",
      questionEn: "Do I need an appointment?",
      answerEn: "No. We welcome walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. You can also call us to reserve a time.",
    },
    {
      question: "¿Atienden a pacientes sin seguro?",
      answer: "Sí. No necesitas seguro médico; manejamos precios accesibles y transparentes. Pregúntanos por el costo antes de tu visita.",
      questionEn: "Do you accept patients without insurance?",
      answerEn: "Yes. You don't need insurance; we offer affordable, transparent pricing. Ask us about the cost before your visit.",
    },
  ],
  "electrocardiograma": [
    {
      question: "¿El electrocardiograma duele o da corriente?",
      answer: "No. Los electrodos solo leen la señal eléctrica del corazón; no envían electricidad al cuerpo. Sentirás únicamente los parches adhesivos en la piel.",
      questionEn: "Does an EKG hurt or give a shock?",
      answerEn: "No. The electrodes only read the heart's electrical signal; they send no electricity into the body. You only feel the adhesive patches on your skin.",
    },
    {
      question: "¿Cuánto tarda el EKG y cuándo me dan el resultado?",
      answer: "El estudio dura unos 5 minutos y el médico lo interpreta en la misma visita. Sales con el trazo impreso y la explicación.",
      questionEn: "How long does the EKG take and when do I get the result?",
      answerEn: "The test takes about 5 minutes and the physician interprets it during the same visit. You leave with the printed tracing and the explanation.",
    },
    {
      question: "¿Cómo me preparo para el electrocardiograma?",
      answer: "Ven con ropa de dos piezas, sin cremas ni aceites en el pecho, y evita café y cigarro durante la hora previa. No necesitas ayuno.",
      questionEn: "How do I prepare for an electrocardiogram?",
      answerEn: "Wear two-piece clothing, no creams or oils on your chest, and avoid coffee and cigarettes for the hour before. No fasting needed.",
    },
    {
      question: "¿Necesito orden médica para hacerme un EKG?",
      answer: "No. Puedes venir directamente; el médico de la clínica evalúa tus síntomas, hace el estudio y lo interpreta. Si traes una orden de otro doctor, le enviamos el trazo.",
      questionEn: "Do I need a doctor's order for an EKG?",
      answerEn: "No. You can come directly; the clinic physician evaluates your symptoms, performs the test and interprets it. If you bring an order from another doctor, we send them the tracing.",
    },
    {
      question: "Si el EKG sale alterado, ¿qué sigue?",
      answer: "El médico te explica el hallazgo, completa con análisis de sangre si hace falta y te refiere con un cardiólogo con el trazo impreso. Si el resultado sugiere algo urgente, te indicamos ir a un hospital de inmediato.",
      questionEn: "If the EKG is abnormal, what happens next?",
      answerEn: "The physician explains the finding, adds blood work if needed and refers you to a cardiologist with the printed tracing. If the result suggests something urgent, we direct you to a hospital right away.",
    },
    {
      question: "¿Necesito cita o seguro para el electrocardiograma?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM, y no necesitas seguro; el EKG con interpretación tiene precio fijo.",
      questionEn: "Do I need an appointment or insurance for an EKG?",
      answerEn: "No. We see walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM, and no insurance is needed; the EKG with interpretation has a flat price.",
    },
  ],
  "ultrasonido": [
    {
      question: "¿Necesito orden médica para hacerme un ultrasonido?",
      answer: "No. Puedes venir directamente y el médico de la clínica evalúa qué estudio necesitas. Si traes una orden de otro doctor, la seguimos y le enviamos el reporte.",
      questionEn: "Do I need a doctor's order for an ultrasound?",
      answerEn: "No. You can come directly and the clinic physician determines which exam you need. If you bring an order from another doctor, we follow it and send them the report.",
    },
    {
      question: "¿Cuándo me dan los resultados del ultrasonido?",
      answer: "En la misma visita. El médico interpreta el estudio en el momento, te muestra las imágenes y te entrega el reporte escrito.",
      questionEn: "When do I get the ultrasound results?",
      answerEn: "During the same visit. The physician interprets the study on the spot, shows you the images and gives you the written report.",
    },
    {
      question: "¿Desde qué semana se ve el embarazo en el ultrasonido?",
      answer: "Alrededor de la sexta semana suele verse el saco gestacional y poco después el latido. Si es muy temprano, te indicamos cuándo repetirlo.",
      questionEn: "How early can a pregnancy be seen on ultrasound?",
      answerEn: "Around the sixth week the gestational sac is usually visible, with the heartbeat shortly after. If it is very early, we tell you when to repeat it.",
    },
    {
      question: "¿Cómo me preparo para un ultrasonido abdominal?",
      answer: "Ven con 6 a 8 horas de ayuno para que la vesícula se vea bien; puedes tomar agua. Para el pélvico o de embarazo temprano necesitas la vejiga llena.",
      questionEn: "How do I prepare for an abdominal ultrasound?",
      answerEn: "Come after fasting 6 to 8 hours so the gallbladder shows clearly; water is fine. For a pelvic or early-pregnancy ultrasound you need a full bladder.",
    },
    {
      question: "¿El ultrasonido es seguro durante el embarazo?",
      answer: "Sí. No usa radiación ni duele; usa ondas de sonido, por eso es el estudio de rutina en el embarazo y se puede repetir cuando haga falta.",
      questionEn: "Is ultrasound safe during pregnancy?",
      answerEn: "Yes. It uses no radiation and does not hurt; it works with sound waves, which is why it is the routine exam in pregnancy and can be repeated whenever needed.",
    },
    {
      question: "¿Cuánto cuesta un ultrasonido sin seguro?",
      answer: "El precio es fijo y depende del tipo de estudio. Llámanos y te lo decimos antes de tu visita; no necesitas seguro ni cita, atendemos de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM.",
      questionEn: "How much does an ultrasound cost without insurance?",
      answerEn: "The price is flat and depends on the type of exam. Call us and we tell you before your visit; no insurance or appointment needed, we are open Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM.",
    },
  ],
  "examen-dot": [
    {
      question: "¿Qué debo traer al examen DOT?",
      answer: "Tu licencia de conducir vigente, lentes o audífonos si los usas y la lista de tus medicamentos. Si tienes presión alta, diabetes o apnea del sueño, trae tus últimos resultados para agilizar el certificado.",
      questionEn: "What should I bring to the DOT exam?",
      answerEn: "Your valid driver's license, glasses or hearing aids if you use them, and your medication list. If you have high blood pressure, diabetes or sleep apnea, bring your latest results to speed up the certificate.",
    },
    {
      question: "¿Me entregan el certificado DOT el mismo día?",
      answer: "Sí, al terminar el examen físico DOT te entregamos tu certificado el mismo día.",
      questionEn: "Do I get the DOT certificate the same day?",
      answerEn: "Yes, after the DOT physical we give you your certificate the same day.",
    },
    {
      question: "¿Necesito cita previa?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. También puedes llamarnos para reservar un horario.",
      questionEn: "Do I need an appointment?",
      answerEn: "No. We welcome walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. You can also call us to reserve a time.",
    },
    {
      question: "¿Atienden a pacientes sin seguro?",
      answer: "Sí. No necesitas seguro médico; manejamos precios accesibles y transparentes. Pregúntanos por el costo antes de tu visita.",
      questionEn: "Do you accept patients without insurance?",
      answerEn: "Yes. You don't need insurance; we offer affordable, transparent pricing. Ask us about the cost before your visit.",
    },
  ],
  "examenes-inmigracion": [
    {
      question: "¿El examen de inmigración incluye examen físico?",
      answer: "Sí. El I-693 incluye un examen físico completo, revisión de vacunas, prueba de tuberculosis y las demás pruebas que exige USCIS. Todo se hace en la clínica.",
      questionEn: "Does the immigration exam include a physical exam?",
      answerEn: "Yes. The I-693 includes a complete physical exam, vaccine review, tuberculosis test and the other tests USCIS requires. Everything is done at the clinic.",
    },
    {
      question: "¿El médico está autorizado por USCIS?",
      answer: "Sí, el examen lo realiza un médico autorizado (civil surgeon) y te entregamos el Formulario I-693 sellado.",
      questionEn: "Is the doctor authorized by USCIS?",
      answerEn: "Yes, the exam is performed by an authorized civil surgeon and we give you the sealed Form I-693.",
    },
    {
      question: "¿Necesito cita previa?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. También puedes llamarnos para reservar un horario.",
      questionEn: "Do I need an appointment?",
      answerEn: "No. We welcome walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. You can also call us to reserve a time.",
    },
    {
      question: "¿Atienden a pacientes sin seguro?",
      answer: "Sí. No necesitas seguro médico; manejamos precios accesibles y transparentes. Pregúntanos por el costo antes de tu visita.",
      questionEn: "Do you accept patients without insurance?",
      answerEn: "Yes. You don't need insurance; we offer affordable, transparent pricing. Ask us about the cost before your visit.",
    },
  ],
  "vacunas": [
    {
      question: "¿Cuándo debo ponerme la vacuna de la flu?",
      answer: "Lo ideal es en septiembre u octubre, antes de que empiece la temporada de gripe en Houston, pero sirve hasta la primavera. La protección tarda unas dos semanas en desarrollarse y hay que repetirla cada año.",
      questionEn: "When should I get my flu shot?",
      answerEn: "Ideally in September or October, before flu season starts in Houston, but it is still useful through spring. Protection takes about two weeks to develop and the shot must be repeated every year.",
    },
    {
      question: "¿Cada cuánto necesito el refuerzo del tétanos?",
      answer: "Cada 10 años. Si tienes una herida sucia o profunda y pasaron más de 5 años desde tu última dosis, conviene ponerte el refuerzo dentro de las primeras 48 horas.",
      questionEn: "How often do I need a tetanus booster?",
      answerEn: "Every 10 years. If you have a dirty or deep wound and more than 5 years have passed since your last dose, you should get the booster within the first 48 hours.",
    },
    {
      question: "¿La vacuna de la influenza me puede dar gripe?",
      answer: "No. La vacuna no contiene virus vivo. Puedes sentir dolor en el brazo, cansancio leve o unas décimas de fiebre uno o dos días; eso es la respuesta normal del cuerpo, no gripe.",
      questionEn: "Can the flu shot give me the flu?",
      answerEn: "No. The vaccine contains no live virus. You may feel a sore arm, mild tiredness or a slight fever for a day or two; that is your body's normal response, not the flu.",
    },
    {
      question: "¿Vacunan a niños?",
      answer: "Aplicamos la vacuna de la influenza a niños y adultos; para menores de 3 años llámanos antes para confirmar disponibilidad de la dosis pediátrica. Los menores deben venir con su padre, madre o tutor.",
      questionEn: "Do you vaccinate children?",
      answerEn: "We give the flu vaccine to children and adults; for kids under 3, call ahead to confirm the pediatric dose is in stock. Minors must come with a parent or legal guardian.",
    },
    {
      question: "¿Me dan comprobante para el trabajo o la escuela?",
      answer: "Sí. Te entregamos un comprobante con la vacuna aplicada, la fecha y el lote, y si traes el formulario de tu empleador o escuela lo llenamos en la misma visita.",
      questionEn: "Will I get proof of vaccination for work or school?",
      answerEn: "Yes. You receive a record with the vaccine given, the date and the lot number, and if you bring your employer or school form we fill it out during the same visit.",
    },
    {
      question: "¿Necesito cita o seguro para vacunarme?",
      answer: "Ninguno de los dos. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM, con precio fijo que te confirmamos por teléfono.",
      questionEn: "Do I need an appointment or insurance to get vaccinated?",
      answerEn: "Neither. We see walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM, at a flat price we can confirm by phone.",
    },
  ],
  "sueros-vitaminados": [
    {
      question: "¿Cuánto dura una sesión de suero vitaminado?",
      answer: "Entre 30 y 60 minutos de infusión, más unos minutos de evaluación antes y de observación después. En total calcula alrededor de una hora.",
      questionEn: "How long does a vitamin drip session take?",
      answerEn: "30 to 60 minutes of infusion, plus a few minutes of evaluation before and observation after. Plan on about an hour in total.",
    },
    {
      question: "¿Cada cuánto puedo ponerme un suero?",
      answer: "Depende de tu objetivo. Para deshidratación o malestar puntual basta con una sesión; como apoyo de energía algunas personas lo repiten cada 2 a 4 semanas. El médico te recomienda la frecuencia adecuada en la evaluación.",
      questionEn: "How often can I get a drip?",
      answerEn: "It depends on your goal. For dehydration or a one-time slump a single session is enough; as an energy support some people repeat it every 2 to 4 weeks. The physician recommends the right frequency during the evaluation.",
    },
    {
      question: "¿Duele la aplicación del suero?",
      answer: "Solo el piquete inicial, parecido a una toma de sangre. Durante la infusión puedes sentir un poco de frío en el brazo, pero no dolor.",
      questionEn: "Does the IV hurt?",
      answerEn: "Only the initial poke, similar to a blood draw. During the infusion you may feel a little coolness in the arm, but no pain.",
    },
    {
      question: "¿Sirve el suero para la resaca o cruda?",
      answer: "Sí. Rehidrata rápido y, si hace falta, incluimos medicamento para las náuseas y el dolor de cabeza. La mayoría de las personas se sienten mejor al terminar la sesión.",
      questionEn: "Does a drip help with a hangover?",
      answerEn: "Yes. It rehydrates quickly and, if needed, we include medication for nausea and headache. Most people feel better by the end of the session.",
    },
    {
      question: "¿Puedo ponerme un suero si estoy embarazada o tengo problemas de riñón?",
      answer: "Debes comentarlo antes. El médico evalúa tu caso y decide si es seguro y qué componentes usar; en insuficiencia renal o cardíaca puede no ser recomendable.",
      questionEn: "Can I get a drip if I am pregnant or have kidney problems?",
      answerEn: "You must mention it first. The physician evaluates your case and decides whether it is safe and which ingredients to use; with kidney or heart failure it may not be advisable.",
    },
    {
      question: "¿Necesito cita y cuánto cuesta?",
      answer: "No necesitas cita ni seguro. El precio es fijo según el suero; llámanos para confirmarlo. Atendemos de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM.",
      questionEn: "Do I need an appointment and how much does it cost?",
      answerEn: "No appointment or insurance needed. The price is flat depending on the drip; call us to confirm it. We are open Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM.",
    },
  ],
  "suturas-heridas": [
    {
      question: "¿Cuánto tiempo tengo para que me pongan puntos?",
      answer: "Lo ideal es dentro de las primeras 6 a 8 horas; en la cara hasta 24 horas. Después de ese tiempo el riesgo de infección sube y puede que ya no se pueda suturar, así que ven el mismo día.",
      questionEn: "How long do I have to get stitches?",
      answerEn: "Ideally within the first 6 to 8 hours; on the face up to 24 hours. After that the infection risk rises and stitching may no longer be possible, so come the same day.",
    },
    {
      question: "¿Duele que te pongan puntos?",
      answer: "Solo el piquete de la anestesia local. Después no sientes dolor mientras limpiamos y cerramos la herida. En niños y heridas pequeñas de la cara a veces usamos pegamento quirúrgico, sin aguja.",
      questionEn: "Do stitches hurt?",
      answerEn: "Only the poke of the local anesthetic. After that you feel no pain while we clean and close the wound. In children and small facial wounds we sometimes use skin glue, no needle.",
    },
    {
      question: "¿Necesito la vacuna del tétanos?",
      answer: "Si tu última dosis fue hace más de 10 años, o hace más de 5 y la herida está sucia, sí. Te la aplicamos en la misma visita.",
      questionEn: "Do I need a tetanus shot?",
      answerEn: "If your last dose was more than 10 years ago, or more than 5 and the wound is dirty, yes. We give it to you during the same visit.",
    },
    {
      question: "¿Cuándo me quitan los puntos y tiene costo?",
      answer: "Según la zona: cara 5 a 7 días, tronco 7 a 10, brazos y piernas 10 a 14. El retiro está incluido en el precio del procedimiento.",
      questionEn: "When are the stitches removed and is there a charge?",
      answerEn: "Depending on the area: face 5 to 7 days, trunk 7 to 10, arms and legs 10 to 14. Removal is included in the price of the procedure.",
    },
    {
      question: "¿Me puedo bañar con los puntos?",
      answer: "Después de 24 a 48 horas puedes ducharte dejando correr el agua sobre la herida, sin remojarla. Evita piscina, bahía y tina hasta que se retiren los puntos.",
      questionEn: "Can I shower with stitches?",
      answerEn: "After 24 to 48 hours you can shower letting water run over the wound, without soaking it. Avoid pools, the bay and bathtubs until the stitches are removed.",
    },
    {
      question: "¿Atienden heridas sin cita y sin seguro?",
      answer: "Sí. Ven directamente de lunes a sábado de 9 AM a 9 PM o domingo de 9 AM a 7 PM. No necesitas seguro; el procedimiento tiene precio fijo que te decimos antes de empezar.",
      questionEn: "Do you treat wounds without an appointment or insurance?",
      answerEn: "Yes. Come directly Monday to Saturday from 9 AM to 9 PM or Sunday from 9 AM to 7 PM. No insurance needed; the procedure has a flat price we tell you before starting.",
    },
  ],
  "curacion-heridas": [
    {
      question: "¿Cada cuánto debo venir a la curación?",
      answer: "Depende de la herida: las que supuran o están infectadas cada 1 o 2 días al inicio; las postoperatorias limpias cada 3 a 5 días; las quemaduras según el apósito. Te damos el plan por escrito en la primera visita.",
      questionEn: "How often do I need to come for wound care?",
      answerEn: "It depends on the wound: draining or infected wounds every 1 or 2 days at first; clean post-surgical wounds every 3 to 5 days; burns according to the dressing. We give you a written plan at the first visit.",
    },
    {
      question: "¿Atienden quemaduras?",
      answer: "Sí, quemaduras de primer grado y de segundo grado superficiales, como las de aceite, agua caliente, vapor o plancha. Las quemaduras extensas, profundas, en cara o genitales, o por químicos o electricidad, deben ir a urgencias.",
      questionEn: "Do you treat burns?",
      answerEn: "Yes, first-degree and superficial second-degree burns, such as from oil, hot water, steam or an iron. Extensive or deep burns, burns on the face or genitals, or chemical or electrical burns should go to the emergency room.",
    },
    {
      question: "¿Pueden quitar los puntos o grapas de mi cirugía?",
      answer: "Sí, cuando tu cirujano lo indique. Trae la hoja de alta o las indicaciones para hacerlo en la fecha correcta, y revisamos la incisión en la misma visita.",
      questionEn: "Can you remove the stitches or staples from my surgery?",
      answerEn: "Yes, when your surgeon indicates it. Bring your discharge paperwork or instructions so we do it on the right date, and we check the incision during the same visit.",
    },
    {
      question: "Tengo diabetes y una llaga en el pie que no duele, ¿debo venir?",
      answer: "Sí, hoy mismo. En diabetes la falta de sensibilidad hace que las heridas avancen sin dolor. Una curación temprana y el control del azúcar evitan infecciones graves y hospitalizaciones.",
      questionEn: "I have diabetes and a painless sore on my foot. Should I come in?",
      answerEn: "Yes, today. With diabetes, loss of sensation lets wounds progress without pain. Early wound care and blood sugar control prevent serious infections and hospital stays.",
    },
    {
      question: "¿Puedo hacer los cambios de vendaje en casa?",
      answer: "Algunos sí. Te enseñamos la técnica, te decimos qué material comprar y programamos revisiones en la clínica para vigilar que la herida avance bien.",
      questionEn: "Can I do the dressing changes at home?",
      answerEn: "Some, yes. We teach you the technique, tell you what supplies to buy and schedule check-ups at the clinic to make sure the wound is progressing well.",
    },
    {
      question: "¿Necesito cita o seguro para las curaciones?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. No necesitas seguro; cada curación tiene precio fijo que te informamos antes.",
      questionEn: "Do I need an appointment or insurance for wound care?",
      answerEn: "No. We see walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. No insurance needed; each visit has a flat price we tell you beforehand.",
    },
  ],
  "cirugias-menores": [
    {
      question: "¿Qué cirugías menores realizan?",
      answer: "Retiro de lunares, verrugas, quistes sebáceos, lipomas, fibromas blandos y cuerpos extraños, además de biopsias de piel, uñas encarnadas y drenaje de abscesos. Todo ambulatorio y con anestesia local.",
      questionEn: "What minor surgeries do you perform?",
      answerEn: "Removal of moles, warts, sebaceous cysts, lipomas, skin tags and foreign bodies, plus skin biopsies, ingrown toenails and abscess drainage. All outpatient and under local anesthesia.",
    },
    {
      question: "¿Duele el procedimiento?",
      answer: "Solo el piquete de la anestesia local. Durante el procedimiento puedes sentir presión o movimiento, pero no dolor. Después basta con analgésico común uno o dos días.",
      questionEn: "Does the procedure hurt?",
      answerEn: "Only the poke of the local anesthetic. During the procedure you may feel pressure or movement, but no pain. Afterward, common pain relievers for a day or two are enough.",
    },
    {
      question: "¿Lo hacen el mismo día de la consulta?",
      answer: "En la mayoría de los casos sí: el médico evalúa la lesión y, si procede, la retira en esa misma visita. Si tomas anticoagulantes o la lesión requiere preparación, te damos fecha.",
      questionEn: "Do you do it the same day as the consultation?",
      answerEn: "In most cases yes: the physician evaluates the lesion and, if appropriate, removes it during that same visit. If you take blood thinners or the lesion requires preparation, we give you a date.",
    },
    {
      question: "¿Analizan el lunar o el quiste que me quitan?",
      answer: "Cuando la lesión lo amerita, la enviamos a patología y te avisamos el resultado en 1 a 2 semanas. Si un lunar tiene características sospechosas, te referimos con dermatología antes de retirarlo.",
      questionEn: "Do you analyze the mole or cyst you remove?",
      answerEn: "When the lesion warrants it, we send it to pathology and let you know the result in 1 to 2 weeks. If a mole has suspicious features, we refer you to dermatology before removing it.",
    },
    {
      question: "¿Cuándo puedo volver a trabajar?",
      answer: "Generalmente al día siguiente. Evita esfuerzos con la zona operada durante una semana si hubo puntos, y mantén el vendaje seco las primeras 24 horas.",
      questionEn: "When can I go back to work?",
      answerEn: "Usually the next day. Avoid straining the operated area for a week if there were stitches, and keep the dressing dry for the first 24 hours.",
    },
    {
      question: "¿Necesito cita o seguro para una cirugía menor?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. No necesitas seguro; el precio depende del procedimiento y te lo confirmamos antes de empezar.",
      questionEn: "Do I need an appointment or insurance for minor surgery?",
      answerEn: "No. We see walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. No insurance needed; the price depends on the procedure and we confirm it before starting.",
    },
  ],
  "drenaje-abscesos": [
    {
      question: "¿El drenaje de un absceso duele?",
      answer: "Aplicamos anestesia local antes de la incisión, así que sientes el piquete inicial y luego presión, no dolor. Al drenar el pus el alivio es inmediato porque baja la presión del bulto.",
      questionEn: "Does abscess drainage hurt?",
      answerEn: "We apply local anesthesia before the incision, so you feel the initial poke and then pressure, not pain. Once the pus drains, relief is immediate because the pressure in the lump drops.",
    },
    {
      question: "¿No basta con tomar antibiótico?",
      answer: "No. El antibiótico no penetra bien en la bolsa de pus; el absceso tiene que drenarse. El antibiótico se agrega solo cuando hay infección alrededor, fiebre, diabetes o el absceso está en la cara.",
      questionEn: "Is an antibiotic not enough?",
      answerEn: "No. Antibiotics do not penetrate the pocket of pus well; the abscess has to be drained. An antibiotic is added only when there is surrounding infection, fever, diabetes or the abscess is on the face.",
    },
    {
      question: "¿Puedo reventarlo yo en casa?",
      answer: "No lo recomendamos. Exprimirlo empuja la infección hacia adentro y puede extenderla. Las compresas tibias ayudan en forúnculos pequeños; si crece o duele mucho, ven a que lo drenemos con técnica estéril.",
      questionEn: "Can I pop it myself at home?",
      answerEn: "We do not recommend it. Squeezing pushes the infection deeper and can spread it. Warm compresses help with small boils; if it grows or hurts a lot, come so we can drain it with sterile technique.",
    },
    {
      question: "¿Cuánto tarda en sanar después del drenaje?",
      answer: "Entre 1 y 2 semanas. Regresas en 24 a 48 horas para retirar la mecha y revisar la cavidad, y la herida cierra sola desde adentro; no se sutura para no atrapar la infección.",
      questionEn: "How long does it take to heal after drainage?",
      answerEn: "1 to 2 weeks. You come back in 24 to 48 hours to remove the wick and check the cavity, and the wound closes on its own from the inside; it is not stitched so the infection is not trapped.",
    },
    {
      question: "¿Por qué me salen abscesos seguido?",
      answer: "Las causas más comunes son ser portador de estafilococo en la piel, diabetes no controlada, sudor y roce bajo la ropa de trabajo, o rasurado. Revisamos tu glucosa y te damos un plan para reducir las recaídas.",
      questionEn: "Why do I keep getting abscesses?",
      answerEn: "The most common causes are carrying staph on the skin, uncontrolled diabetes, sweat and friction under work clothes, or shaving. We check your blood sugar and give you a plan to reduce recurrences.",
    },
    {
      question: "¿Necesito cita o seguro para drenar un absceso?",
      answer: "No. Ven directamente de lunes a sábado de 9 AM a 9 PM o domingo de 9 AM a 7 PM. No necesitas seguro; el drenaje tiene precio fijo que te decimos antes de empezar.",
      questionEn: "Do I need an appointment or insurance to have an abscess drained?",
      answerEn: "No. Come directly Monday to Saturday from 9 AM to 9 PM or Sunday from 9 AM to 7 PM. No insurance needed; drainage has a flat price we tell you before starting.",
    },
  ],
  "unas-encarnadas": [
    {
      question: "¿Cómo tratan la uña encarnada?",
      answer: "Según la etapa. Si es leve, levantamos el borde y te enseñamos cuidados. Si hay infección o dolor intenso, con anestesia local retiramos solo la franja lateral de la uña que se clava, y si se ha repetido, tratamos la raíz para que no vuelva a crecer por ese lado.",
      questionEn: "How do you treat an ingrown toenail?",
      answerEn: "Depending on the stage. If mild, we lift the edge and teach you care. If there is infection or severe pain, under local anesthesia we remove only the side strip of nail that is digging in, and if it has recurred, we treat the root so it does not grow back on that side.",
    },
    {
      question: "¿Me quitan toda la uña?",
      answer: "No. Solo retiramos la franja lateral de 2 a 3 milímetros que se está clavando. La uña conserva un aspecto casi normal.",
      questionEn: "Do you remove the whole nail?",
      answerEn: "No. We remove only the 2 to 3 millimeter side strip that is digging in. The nail keeps an almost normal appearance.",
    },
    {
      question: "¿Duele el procedimiento?",
      answer: "Solo la anestesia en la base del dedo, que son uno o dos piquetes. Después no sientes dolor. Al pasar la anestesia, unas 2 horas después, se controla con analgésico común.",
      questionEn: "Does the procedure hurt?",
      answerEn: "Only the anesthetic at the base of the toe, which is one or two pokes. After that you feel no pain. When it wears off, about 2 hours later, common pain relievers control it.",
    },
    {
      question: "¿Cuándo puedo volver a trabajar o usar botas?",
      answer: "A la mayoría de los trabajos en 1 o 2 días. Si usas bota de seguridad, espera 3 a 5 días o usa una protección sobre el dedo. Trae una sandalia el día del procedimiento porque el dedo va vendado.",
      questionEn: "When can I go back to work or wear boots?",
      answerEn: "To most jobs in 1 or 2 days. If you wear safety boots, wait 3 to 5 days or use a protector over the toe. Bring a sandal on the day of the procedure because the toe will be bandaged.",
    },
    {
      question: "¿Puede volver a encarnarse?",
      answer: "Si se retira solo la franja sin tratar la raíz, puede volver. Cuando el problema se ha repetido aplicamos fenol en la raíz de esa franja, lo que reduce mucho la recaída. Cortar la uña recta y usar calzado amplio también ayuda.",
      questionEn: "Can it become ingrown again?",
      answerEn: "If only the strip is removed without treating the root, it can. When the problem has recurred we apply phenol to the root of that strip, which greatly reduces recurrence. Cutting the nail straight and wearing roomy footwear also helps.",
    },
    {
      question: "¿Necesito cita o seguro para tratar la uña encarnada?",
      answer: "No. Atendemos sin cita de lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM. No necesitas seguro; el procedimiento tiene precio fijo que te informamos antes.",
      questionEn: "Do I need an appointment or insurance for ingrown toenail treatment?",
      answerEn: "No. We see walk-ins Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM. No insurance needed; the procedure has a flat price we tell you beforehand.",
    },
  ],
  "farmacia": [
    {
      question: "¿Puedo surtir mi receta en la clínica?",
      answer: "Sí. El médico la envía a nuestra farmacia mientras terminas la consulta y la recoges en minutos, con la explicación de cómo tomarla. Si algo no está en existencia, te damos la receta impresa para surtirla donde prefieras.",
      questionEn: "Can I fill my prescription at the clinic?",
      answerEn: "Yes. The physician sends it to our pharmacy while you finish your visit and you pick it up in minutes, with an explanation of how to take it. If something is out of stock, we give you the printed prescription to fill wherever you prefer.",
    },
    {
      question: "¿Surten recetas de otros médicos?",
      answer: "Solo recetas de la clínica o de médicos externos que podamos verificar, y nunca sustancias controladas. Si necesitas un medicamento que no manejamos, te orientamos sobre dónde conseguirlo.",
      questionEn: "Do you fill prescriptions from other doctors?",
      answerEn: "Only prescriptions from the clinic or from outside doctors we can verify, and never controlled substances. If you need a medication we do not carry, we guide you on where to get it.",
    },
    {
      question: "¿Cuánto cuestan los medicamentos sin seguro?",
      answer: "Trabajamos sobre todo con genéricos, a una fracción del precio de marca, y te decimos el costo antes de despachar. No necesitas seguro; aceptamos efectivo y tarjetas.",
      questionEn: "How much do medications cost without insurance?",
      answerEn: "We work mostly with generics, at a fraction of the brand price, and tell you the cost before dispensing. No insurance needed; we accept cash and cards.",
    },
    {
      question: "¿Puedo resurtir mi medicamento de diabetes o presión sin nueva consulta?",
      answer: "Sí, mientras tu receta esté vigente. Cuando esté por vencer te avisamos para programar tu control con el médico y ajustar la dosis si hace falta.",
      questionEn: "Can I refill my diabetes or blood pressure medication without a new visit?",
      answerEn: "Yes, while your prescription is valid. When it is about to expire we let you know so you can schedule your follow-up with the physician and adjust the dose if needed.",
    },
    {
      question: "¿Venden medicamentos sin receta?",
      answer: "Sí, productos de venta libre: antigripales, analgésicos, antihistamínicos, sueros orales, termómetros, material de curación, glucómetros y tiras reactivas. Para antibióticos y medicamentos controlados sí se necesita consulta.",
      questionEn: "Do you sell over-the-counter medications?",
      answerEn: "Yes: cold remedies, pain relievers, antihistamines, oral rehydration solutions, thermometers, wound-care supplies, glucose meters and test strips. Antibiotics and prescription medications do require a visit.",
    },
    {
      question: "¿Cuál es el horario de la farmacia?",
      answer: "El mismo de la clínica: lunes a sábado de 9 AM a 9 PM y domingo de 9 AM a 7 PM, sin cita y con atención en español.",
      questionEn: "What are the pharmacy hours?",
      answerEn: "The same as the clinic: Monday to Saturday from 9 AM to 9 PM and Sunday from 9 AM to 7 PM, no appointment needed, with service in Spanish.",
    },
  ],
};

/** FAQs de un servicio por slug (vacío si no tiene). */
export function getServiceFaqs(slug: string): ServiceFaq[] {
  return SERVICE_FAQS[slug] ?? [];
}
